export enum IncidentStatus {
  REPORTED = 'REPORTED',

  UNDER_INVESTIGATION = 'UNDER_INVESTIGATION',
  ADDITIONAL_INFO_REQUIRED = 'ADDITIONAL_INFO_REQUIRED',

  RESOLVED = 'RESOLVED',
  PARTIALLY_RESOLVED = 'PARTIALLY_RESOLVED',

  CLOSED = 'CLOSED',
  ARCHIVED = 'ARCHIVED',

  DISMISSED = 'DISMISSED',
  PENDING_ACTION = 'PENDING_ACTION'
}
