export enum IncidentType {
  ACCIDENT = 'ACCIDENT',
  NEAR_MISS = 'NEAR_MISS',
  MECHANICAL_ISSUE = 'MECHANICAL_ISSUE',
  SAFETY_CONCERN = 'SAFETY_CONCERN',

  THEFT = 'THEFT',
  DAMAGE = 'DAMAGE',
  MAINTENANCE_ISSUE = 'MAINTENANCE_ISSUE',
  OTHER = 'OTHER'
}
